#OPERACIÓN MATEMÁTICAS...#
a,b = 3,4
print("La suma de 3 + 4 da: ")
print(a+b)
print("La resta de 3-4 da: ")
print(a-b)

print("La multiplicacion de 3*4 números da: ")
print(a*b)

print("La division de 3/4 da: ")
print(round(a/b))

print("El número 3 exponenciado a la 4 da: ")
print(a**b)

print("El modular de 3%4 da: ")
print(a%b)

print("El floor de 3//4 da: ")
print(a//b)
#OPERACIÓN MATEMÁTICAS...#

#NOMBRES#
firstname = input("Dame tu primer nombre: ")
lastname = input("Dame tu apellido: ")
country = input("Dame tu pais de origen: ")
print("Eres ", firstname, " ", lastname, ", ", "eres del pais de ", country, " y estas disfrutando de los 30 dias de programar en python...")
#NOMBRES#

