#OPERACIÓN MATEMÁTICAS...#
a,b = 3,4
print("La suma de 3 + 4 da: ")
print(a+b)
print("La resta de 3-4 da: ")
print(a-b)

print("La multiplicacion de 3*4 números da: ")
print(a*b)

print("La division de 3/4 da: ")
print(round(a/b))

print("El número 3 exponenciado a la 4 da: ")
print(a**b)

print("El modular de 3%4 da: ")
print(a%b)

print("El floor de 3//4 da: ")
print(a//b)
#OPERACIÓN MATEMÁTICAS...#

#NOMBRES#
firstname = input("Dame tu primer nombre: ")
lastname = input("Dame tu apellido: ")
country = input("Dame tu pais de origen: ")
print("Eres ", firstname, " ", lastname, ", ", "eres del pais de ", country, " y estas disfrutando de los 30 dias de programar en python...")
#NOMBRES#

#IDENTIFICACION DEL DATO INTRODUCIDO...#
print("El dato 10 es un entero: ",type(10))          # Int
print("El dato 9.8 es un float: ",type(9.8))        # Float
print("El dato (4 +4j) es un complejo: ",type(4 + 4j))      # Complex number
print("Los elementos en un corchete conforman una lista [Asabeneth, Python, Finland] es una lista...",type(['Asabeneh', 'Python', 'Finland']))  # Lista
print("Tu nombre ", firstname," es un dato tipo string... ",type(firstname))   # String
print("Tu apellido ", lastname, " es un dato tipo string...",type(lastname)) # String
print("Tu país", country,"es un dato tipo string...",type(country))    # String
print(type({9.8, 3.14, 2.7}))    # Set
print(type((9.8, 3.14, 2.7)))    # Tuple

#IDENTIFICACION DEL DATO INTRODUCIDO...#

